version: '3.5'

services:

  currencygraphs:
    container_name: currencygraphs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
      - '80:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=http://35.243.152.136
      - REACT_APP_API_BASE_PORT=8000